# Generated by Django 5.2.4 on 2025-07-12 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(editable=False, help_text='Unique booking identifier', max_length=20, unique=True)),
                ('start_date', models.DateField(help_text='Rental start date')),
                ('end_date', models.DateField(help_text='Rental end date')),
                ('start_time', models.TimeField(default='09:00', help_text='Pickup time')),
                ('end_time', models.TimeField(default='18:00', help_text='Return time')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('daily_rate', models.DecimalField(decimal_places=2, help_text='Daily rate at the time of booking', max_digits=8)),
                ('total_days', models.PositiveIntegerField(help_text='Total rental days')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal (daily_rate * total_days)', max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, help_text='Security deposit amount', max_digits=8)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Discount applied', max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount to be paid', max_digits=10)),
                ('customer_name', models.CharField(help_text='Customer full name', max_length=100)),
                ('customer_email', models.EmailField(help_text='Customer email', max_length=254)),
                ('customer_phone', models.CharField(help_text='Customer phone number', max_length=20)),
                ('customer_address', models.TextField(help_text='Customer address')),
                ('driver_license_number', models.CharField(help_text="Driver's license number", max_length=50)),
                ('pickup_location', models.CharField(help_text='Pickup location', max_length=200)),
                ('return_location', models.CharField(help_text='Return location', max_length=200)),
                ('pickup_notes', models.TextField(blank=True, help_text='Special pickup instructions')),
                ('return_notes', models.TextField(blank=True, help_text='Special return instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('special_requests', models.TextField(blank=True, help_text='Special requests from customer')),
                ('terms_accepted', models.BooleanField(default=False, help_text='Terms and conditions accepted')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for cancellation')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, help_text='Refund amount', max_digits=10)),
                ('cancellation_fee', models.DecimalField(decimal_places=2, default=0, help_text='Cancellation fee', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation', to='bookings.booking')),
                ('cancelled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_cancellations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking Cancellation',
                'verbose_name_plural': 'Booking Cancellations',
                'db_table': 'booking_cancellations',
            },
        ),
        migrations.CreateModel(
            name='BookingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('stripe', 'Stripe')], max_length=20)),
                ('payment_type', models.CharField(choices=[('deposit', 'Deposit'), ('full_payment', 'Full Payment'), ('partial_payment', 'Partial Payment'), ('refund', 'Refund')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='PKR', max_length=3)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('is_successful', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Booking Payment',
                'verbose_name_plural': 'Booking Payments',
                'db_table': 'booking_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer', 'status'], name='bookings_custome_b789e2_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['vehicle', 'status'], name='bookings_vehicle_359ccd_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['start_date', 'end_date'], name='bookings_start_d_527bc3_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_id'], name='bookings_booking_dcd799_idx'),
        ),
    ]
