# Generated by Django 5.2.4 on 2025-07-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(editable=False, help_text='Unique booking identifier', max_length=25, unique=True),
        ),
    ]
